blank_issues_enabled: false
contact_links:
    -
        name: Other feedback
        url: https://alexandra.lu/discord
        about: This repository does not handle feature requests or other types of feedback.
